TASK 1

In [ ]:

sensor_readings = [
    {"time": 0, "temp": 32, "volt": 400, "curr": 20, "charge": 95},
    {"time": 1, "temp": 35, "volt": 395, "curr": 22, "charge": 88},
    {"time": 2, "temp": 38, "volt": 390, "curr": 25, "charge": 80},
    {"time": 3, "temp": 40, "volt": 385, "curr": 28, "charge": 70},
    {"time": 4, "temp": 42, "volt": 380, "curr": 30, "charge": 60},
    {"time": 5, "temp": 45, "volt": 375, "curr": 32, "charge": 48}
]

def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"

print("Time(h) | Temp(°C) | Volt(V) | Current(A) | Charge(%) | Temp Alert             | Battery Alert       | Status")
print("-" * 110)
for row in sensor_readings:
    t_alert = "High Temperature Alert" if row["temp"] > 40 else "Temperature Normal"
    b_alert = "Low Battery Alert" if row["charge"] < 50 else "Battery Charge Normal"
    status = battery_status(row["charge"])

    print(f"{row['time']:<7} | {row['temp']:<8} | {row['volt']:<7} | {row['curr']:<10} | {row['charge']:<9} | {t_alert:<22} | {b_alert:<20} | {status}")


Time(h) | Temp(°C) | Volt(V) | Current(A) | Charge(%) | Temp Alert             | Battery Alert       | Status
--------------------------------------------------------------------------------------------------------------
0       | 32       | 400     | 20         | 95        | Temperature Normal     | Battery Charge Normal | High
1       | 35       | 395     | 22         | 88        | Temperature Normal     | Battery Charge Normal | High
2       | 38       | 390     | 25         | 80        | Temperature Normal     | Battery Charge Normal | High
3       | 40       | 385     | 28         | 70        | Temperature Normal     | Battery Charge Normal | Medium
4       | 42       | 380     | 30         | 60        | High Temperature Alert | Battery Charge Normal | Medium
5       | 45       | 375     | 32         | 48        | High Temperature Alert | Low Battery Alert    | Low


TASK 2:

In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

rows, cols = D.shape
print(f"1. Shape of Array: {rows} Rows, {cols} Columns")
averages = np.mean(D, axis=0)
print(f"2. Averages -> T_bar: {averages[0]:.2f}°C, V_bar: {averages[1]:.2f}V, I_bar: {averages[2]:.2f}A, C_bar: {averages[3]:.2f}%")
t_max, t_min = np.max(D[:, 0]), np.min(D[:, 0])
print(f"3. Temp Limits -> Max Temp: {t_max}°C, Min Temp: {t_min}°C")
V = D[:, 1:2]
print("4. Voltage Column Vector V:\n", V)
high_temp_mask = D[:, 0] > 40
print("5. High Temperature Rows:\n", D[high_temp_mask])
low_battery_mask = D[:, 3] < 50
print("6. Low Battery Rows:\n", D[low_battery_mask])


1. Shape of Array: 6 Rows, 4 Columns
2. Averages -> T_bar: 38.67°C, V_bar: 387.50V, I_bar: 26.17A, C_bar: 73.50%
3. Temp Limits -> Max Temp: 45°C, Min Temp: 32°C
4. Voltage Column Vector V:
 [[400]
 [395]
 [390]
 [385]
 [380]
 [375]]
5. High Temperature Rows:
 [[ 42 380  30  60]
 [ 45 375  32  48]]
6. Low Battery Rows:
 [[ 45 375  32  48]]


TASK 3

In [ ]:
A = np.array([[2, 1], [1, 3]])
X = np.array([40, 25])
B = np.array([100, 120])

Y = A @ X
A_T = A.T
det_A = np.linalg.det(A)
A_inv = np.linalg.inv(A)
solved_vars = np.linalg.solve(A, B)

print(f"Matrix Multiplication Y:\n {Y}")
print(f"Transpose A^T:\n {A_T}")
print(f"Determinant: {det_A:.1f}")
print(f"Inverse A^-1:\n {A_inv}")
print(f"Solved System (x, y): {solved_vars}")


Matrix Multiplication Y:
 [105 115]
Transpose A^T:
 [[2 1]
 [1 3]]
Determinant: 5.0
Inverse A^-1:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
Solved System (x, y): [36. 28.]


TASK 4:

In [ ]:
import sympy as sp

t = sp.symbols('t')
C = 100 - 2*t - 0.5*t**2
dC_dt = sp.diff(C, t)
print(f"1. Analytical Derivative dC/dt: {dC_dt}")
rate_t2 = dC_dt.subs(t, 2)
rate_t5 = dC_dt.subs(t, 5)
print(f"2. Discharge rate at t = 2 hours: {rate_t2}% per hour")
print(f"   Discharge rate at t = 5 hours: {rate_t5}% per hour")
d2C_dt2 = sp.diff(dC_dt, t)
print(f"3. Acceleration (d2C/dt2): {d2C_dt2}")

if d2C_dt2 < 0:
    print("   Interpretation: The battery is losing charge at an INCREASING rate.")
elif d2C_dt2 > 0:
    print("   Interpretation: The battery is losing charge at a DECREASING rate.")
else:
    print("   Interpretation: The battery is losing charge at a CONSTANT rate.")


1. Analytical Derivative dC/dt: -1.0*t - 2
2. Discharge rate at t = 2 hours: -4.00000000000000% per hour
   Discharge rate at t = 5 hours: -7.00000000000000% per hour
3. Acceleration (d2C/dt2): -1.00000000000000
   Interpretation: The battery is losing charge at an INCREASING rate.
