In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40,40,80])
print(arr)

[10 20 30 40 40 80]


In [ ]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr = np.arange(5,26)
print(arr)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [ ]:
arr = np.arange(1,19)
print(arr.reshape(3,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [ ]:
arr = np.array([[1,2,3,5], [4,5,8,6]])
print(arr.shape)
print(arr.size)

(2, 4)
8


In [ ]:
arr = np.linspace(3, 20, 7)
print(arr)

[ 3.          5.83333333  8.66666667 11.5        14.33333333 17.16666667
 20.        ]


In [ ]:
arr = np.eye(10)
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
arr = np.full((5, 10), 16)
print(arr)

[[16 16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16 16]
 [16 16 16 16 16 16 16 16 16 16]]


In [ ]:
arr = np.array([[1, 2, 3,4],[7, 8, 9,5]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 4)
2
8
int64
[[1 7]
 [2 8]
 [3 9]
 [4 5]]


In [ ]:
arr = np.array([
    [[9, 4, 9],
     [2,9,6],
     [3, 5, 3]],


    [[7, 8, 9],
     [8,3,0],
     [10, 11, 12]]
])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr[0])
print(arr[1])
print(arr[0][1])
print(arr[1][0][0])

[[[ 9  4  9]
  [ 2  9  6]
  [ 3  5  3]]

 [[ 7  8  9]
  [ 8  3  0]
  [10 11 12]]]
3
(2, 3, 3)
18
[[9 4 9]
 [2 9 6]
 [3 5 3]]
[[ 7  8  9]
 [ 8  3  0]
 [10 11 12]]
[2 9 6]
7


In [ ]:
import numpy as np
arr = np.array([9,1,8,2,6,1,4,0,9,])
new_arr = arr.reshape(3, 3)
print(new_arr)

[[9 1 8]
 [2 6 1]
 [4 0 9]]


In [ ]:
arr = np.array([8,3,0,4,1,2,5,0,])
new_arr_1 = np.reshape(arr,(2,4))
print(new_arr_1)

[[8 3 0 4]
 [1 2 5 0]]


In [ ]:
arr_3d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
new_arr_3d = arr_3d.reshape(3,3,2)
print(new_arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [ ]:
import numpy as np
arr = np.array([8,3,4,1,4,6,2,5,0,5])
print(arr[1:4])
print(arr[:3])
print(arr[1:])
print(arr[::3])

[3 4 1]
[8 3 4]
[3 4 1 4 6 2 5 0 5]
[8 1 2 5]


In [ ]:
import numpy as np
arr = np.array([[9,8,6],
                [9,7,7],
                [8,8,9]])
print(arr[0:2,1:3])
print(arr[2,:3])
print(arr[:,2])

[[8 6]
 [7 7]]
[8 8 9]
[6 7 9]


In [ ]:
import numpy as np
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
print(arr[1,:,:])
print(arr[1,0,:])
print(arr[:,:,1])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]
[[ 2  5]
 [ 8 11]]


In [ ]:
import numpy as np

a = np.array([9,4,9])
b = np.array([3,5,3])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [12  9 12]
Subtraction: [ 6 -1  6]
Multiplication: [27 20 27]
Division: [3.  0.8 3. ]
Floor Division: [3 0 3]
Modulus: [0 4 0]
Power: [81 16 81]


In [ ]:
import numpy as np
arr = np.array([16,1,2,2,6,6])
print("Original Array:", arr)
print("\nSquare Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))
arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))
print("\nExponential:", np.exp(arr))
print("\nNatural Log:", np.log(arr))
print("Log Base 10:", np.log10(arr))
print("\nSine:", np.sin(arr))
print("Cosine:", np.cos(arr))
print("Tangent:", np.tan(arr))
decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))
print("Ceiling:", np.ceil(decimal))
print("Floor:", np.floor(decimal))

Original Array: [16  1  2  2  6  6]

Square Root: [4.         1.         1.41421356 1.41421356 2.44948974 2.44948974]
Square: [256   1   4   4  36  36]
Cube: [4096    1    8    8  216  216]

Absolute Value: [ 5 10 15 20 25]

Exponential: [8.88611052e+06 2.71828183e+00 7.38905610e+00 7.38905610e+00
 4.03428793e+02 4.03428793e+02]

Natural Log: [2.77258872 0.         0.69314718 0.69314718 1.79175947 1.79175947]
Log Base 10: [1.20411998 0.         0.30103    0.30103    0.77815125 0.77815125]

Sine: [-0.28790332  0.84147098  0.90929743  0.90929743 -0.2794155  -0.2794155 ]
Cosine: [-0.95765948  0.54030231 -0.41614684 -0.41614684  0.96017029  0.96017029]
Tangent: [ 0.30063224  1.55740772 -2.18503986 -2.18503986 -0.29100619 -0.29100619]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
import numpy as np
marks = np.array([9,4,9,3,5,3,2,8,6,6])

print("Original Array:", marks)
print("Sorted Array:", np.sort(marks))
print("\nSum:", np.sum(marks))
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Range:", np.ptp(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Index of Maximum:", np.argmax(marks))
print("Index of Minimum:", np.argmin(marks))
print("25th Percentile:", np.percentile(marks, 25))
print("50th Percentile:", np.percentile(marks, 50))
print("75th Percentile:", np.percentile(marks, 75))

Original Array: [9 4 9 3 5 3 2 8 6 6]
Sorted Array: [2 3 3 4 5 6 6 8 9 9]

Sum: 55
Mean: 5.5
Median: 5.5
Maximum: 9
Minimum: 2
Range: 7
Standard Deviation: 2.4186773244895647
Variance: 5.85
Index of Maximum: 0
Index of Minimum: 6
25th Percentile: 3.25
50th Percentile: 5.5
75th Percentile: 7.5


In [ ]:
import numpy as np
print(np.random.rand())
print(np.random.rand(5))
print(np.random.randint(1, 11, 5))
subjects = ["DBMS", "Python", "Java", "ML"]
print(np.random.choice(subjects))
print(np.random.normal(50, 10, 5))
print(np.random.uniform(10, 20, 5))
print(np.random.binomial(1, 0.5))
print(np.random.binomial(10, 0.7))
print(np.random.poisson(4, 5))
print(np.random.exponential(2, 5))

0.26797757186979454
[0.73716588 0.50564913 0.29476307 0.84836647 0.39045881]
[5 9 4 9 2]
Python
[40.54986763 46.1543426  57.0512928  59.77116736 26.23199266]
[13.15317387 10.51148106 15.54175204 18.18710092 10.77221459]
0
6
[4 5 4 3 3]
[6.25667511 2.12308339 0.70034367 4.49466537 0.71576852]


In [ ]:
scalar=np.array(3)
vector=np.array([9,4,9])
matrix=np.array([[5,6],[9,20]])
tensor=np.ones((9,1,8))

for name, arr in[ ('scalar',scalar) , ('vector',vector),
                  ('matrix',matrix),('tensor',tensor)]:
    print(f'{name:7s} ndim={arr.ndim} shape={arr.shape}')

scalar  ndim=0 shape=()
vector  ndim=1 shape=(3,)
matrix  ndim=2 shape=(2, 2)
tensor  ndim=3 shape=(9, 1, 8)


In [ ]:
A = np.arange(9).reshape(3,3)
B = np.ones((3,3), dtype=int)
print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 3):\n', A.reshape(3, 3))
print('A.flatten():', A.flatten())

A:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
A + B (element-wise add):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A.T  (transpose -> shape (3, 3) ):
 [[0 3 6]
 [1 4 7]
 [2 5 8]]
A.reshape(3, 3):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
A.flatten(): [0 1 2 3 4 5 6 7 8]


In [ ]:
print(5^3)

6
